
INSERT INTO intoreIdentities (fullName, nationalId, gender, mother, father, martialStatus, height, mass, bmi, pressure, vaccination, district, sector, cell, village, firstTel, secondTel, email, school, combination,additionalInfo)
VALUES
('Ishimwe Doe', '123456789', 'Male', 'Jane Doe', 'Peter Doe', 'Single', '170', '70', NULL, NULL, NULL, 'Kigali', 'Nyarugenge', 'Kacyiru', 'Gacaca', '0788888888', NULL, 'johndoe@gmail.com',"Rwamagana Leaders'School",'Math-Physics-Chemistry','lorem hjfhie ssss dfddf dfrtwrtf fesfr'),
('Ineza Jane', '987654321', 'Female', 'Mary Doe', 'Paul Doe', 'Married', '165', '60', NULL, NULL, NULL, 'Kigali', 'Nyarugenge', 'Kacyiru', 'Gacaca', '0787777777', NULL, 'janedoe@gmail.com',"GS Kabusunzu",'Math-Physics-Chemistry','lorem hjfhie ssss dfddf dfrtwrtf fesfr'),
('Peter Doe', '1234567890', 'Male', 'Jane Doe', 'John Doe', 'Single', '175', '75', NULL, NULL, NULL, 'Kigali', 'Nyarugenge', 'Kacyiru', 'Gacaca', NULL, '0786666666', 'peterdoe@gmail.com',"GS Kimisagara",'Nursing','lorem hjfhie ssss dfddf dfrtwrtf fesfr'),
('Iganze Mark', '9876543210', 'Female', 'Susan Doe', 'David Doe', 'Married', '160', '55', NULL, NULL, NULL, 'Kigali', 'Nyarugenge', 'Kacyiru', 'Gacaca', NULL, '0785555555', 'marydoe@gmail.com',"Ecole de science Byimana",'Math-Physics-Chemistry','lorem hjfhie ssss dfddf dfrtwrtf fesfr'),
('Ngabo Derrick', '12345678901', 'Male', 'Jane Doe', 'John Doe', 'Single', '180', '80', NULL, NULL, NULL, 'Kigali', 'Nyarugenge', 'Kacyiru', 'Gacaca', NULL, '0784444444', 'pauldoe@gmail.com',"Gacuriro TCC",'Construction','lorem hjfhie ssss dfddf dfrtwrtf fesfr'),
('John Doe', '1234567892', 'Male', 'Jane Doe', 'Peter Doe', 'Single', '170', '70', NULL, NULL, NULL, 'Kigali', 'Nyarugenge', 'Kacyiru', 'Gacaca', '0788888888', NULL, 'johndoe2@gmail.com',"APACOPE",'Math-Physics-Chemistry','lorem hjfhie ssss dfddf dfrtwrtf fesfr'),
('Uwineza Diane', '9876543212', 'Female', 'Mary Doe', 'Paul Doe', 'Married', '165', '60', NULL, NULL, NULL, 'Kigali', 'Nyarugenge', 'Kacyiru', 'Gacaca', '0787777777', NULL, 'janedoe2@gmail.com',"GS Shyogwe",'Kinyarwanda Dwahili','lorem hjfhie ssss dfddf dfrtwrtf fesfr'),
('Ndayishimiye Emile', '12345678903', 'Male', 'Jane Doe', 'John Doe', 'Single', '175', '75', NULL, NULL, NULL, 'Kigali', 'Nyarugenge', 'Kacyiru', 'Gacaca', NULL, '0786666666', 'peterdoe2@gmail.com',"Riviera High School",'Math-Biology-Chemistry','lorem hjfhie ssss dfddf dfrtwrtf fesfr'),
('Mary Doe', '98765432104', 'Female', 'Susan Doe', 'David Doe', 'Married', '160', '55', NULL, NULL, NULL, 'Kigali', 'Nyarugenge', 'Kacyiru', 'Gacaca', NULL, '0785555555', 'marydoe2@gmail.com',"Corner Stone",'Math-Physics-Geography','lorem hjfhie ssss dfddf dfrtwrtf fesfr'),
('Niyobose Ester', '123456789015', 'Male', 'Jane Doe', 'John Doe', 'Single', '180', '80', NULL, NULL, NULL, 'Kigali', 'Nyarugenge', 'Kacyiru', 'Gacaca', NULL, '0784444444', 'pauldoe2@gmail.com',"TTC Tumba",'Education in Math and Physics','lorem ist do raloero nb  fgs');
